### PR TITLE
New bingo types

### PR DESCRIPTION
**Pull request by styfrombrest**
According to empty week scores I assume that it's very hard to collect current bingo types. I think it's a good idea to add some more.  What do you think?

### CODE REVIEW

**Review by wizzlerr — CHANGES_REQUESTED** [review]
I dont like idea of microbingo. 3 fields in a row happen too often. Lucky bingo is fine, just make it 4 points. Also need to update the table with how many templates you can print after scoring lucky bingo

**Comment by styfrombrest** [comment]
Maybe you're a really lucky guy, but on example "micro bingo" - it's the only one my achievement during whole last week(9 of 25 items are crossed out). And looks like envs started to work normally, so chances are going lower... :)

**Comment by wizzlerr** [comment]
Still 3 is not enough. You can always print 3 templates. Maybe introduce some patterns?

**Comment by styfrombrest** [comment]
Okay with micro bingo.
Table was updated.

**Review by wizzlerr — CHANGES_REQUESTED** [review]
Maybe lucky bingo should let you print more templates? Marking 12 fields and being awarded with 1 template? I think It shoul be 2,1,1? Less than a bingo more than small bingo.

**Comment by styfrombrest** [comment]
That makes sense, agree. Fixed.

**Review by wizzlerr — APPROVED** [review]

**Pull request merged**
